name: ci-golang-workflow
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # go-version: ["1.19", "1.20.5"]
        go-version: ["1.20.5"]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go 1.20.5
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # Final da configuração do ambiente
      - name: Run tests
        run: go test -v

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gusflopes/fc-github-actions:latest
          build-args: |
            VERSION=1.0.0
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=$(git rev-parse --short HEAD)
