name: ci-golang-workflow
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.19", "1.20.5"]
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go 1.20.5
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # Final da configuração do ambiente
      - name: Run tests
        run: go test -v
